### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by pefman** [Cultti/webrcon-cli#1]
Hi!

im getting the following error while using the example 
webrcon-cli 127.0.0.1:28016 p4ssw0rd "say Hello World"

root@rust:/home/pefman/node# webrcon-cli localhost:28016 XXXXXXXXX say "Hello World"
undefined

however commands like status works!

**Comment by Cultti** [comment]
Hi,

It should work, just make sure that the full command is between quotation marks: "say Hello World".

However I did make a small change that it will echo back your command when using say command. This due that Rust will not reply anything to say command execution.
